on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun
      - run: bun install
        name: Install Dependancies
      - run: bun run build
        name: Build binaries
      - uses: softprops/action-gh-release@v2
        name: Draft Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: "${{ github.head_ref }}"
          name: "v${{ github.head_ref }}"
          body: "**Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ github.ref }}...${{ github.head_ref }}\n${{ inputs.body }}"
          draft: true
          make_latest: true
          overwrite_files: true
          files: dist/*/*
