on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun
      - run: bun install
        name: Install Dependancies
      - run: bun run build
        name: Build binaries
      - uses: softprops/action-gh-release@v2
        name: Draft Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: "v${{ github.event.pull_request.head.label }}"
          name: "v${{ github.event.pull_request.head.label }}"
          body: "**Full Changelog**: ${{ github.event.pull_request.diff_url }}\n${{ inputs.body }}"
          draft: true
          make_latest: true
          files: dist/${{ github.event.pull_request.label }}/*
